[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.9"
bincode = {version = "2.0.1", features = ["alloc"]}
methods = { path = "../methods" }
risc0-zkvm = { version = "^3.0.4" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
