[package]
name = "guest_merkle"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.4", default-features = false, features = ['std'] }
sha2 = "0.10.9"
bincode = {version = "2.0.1", features = ["alloc"]}
