[package]
name = "encoder"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1", features = ["std"] }
serde = "1.0.228"
serde_json = "1.0.145"
merkle_lib = {path="../merkle-lib"}
sha2 = {version = "0.10.9"}
