[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.4.1", features = ["std"] }
sha2 = "0.10.9"
merkle_lib = {path="../merkle-lib"}
