[package]
version = "0.1.0"
name = "merkle-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.0.8"
merkle-verify = { path = "../lib" }
sha2 = {version = "0.10.9"}
